version: 2
jobs:
    build:
        working_directory: /home/circleci/duo-contract-wrapper
        docker: 
            - image: circleci/node:8.11.1
        steps:
            - checkout
            - run: cd /home/circleci/duo-contract-wrapper
            - run:
                name: Install npm wee
                command: npm install
            - run:
                name: test coverage
            	command: npm test -- --coverage
            - save_cache:
                key: dependency-test-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - /home/circleci/duo-contract-wrapper
    deploy:
        docker:
            - image: circleci/python:2.7-jessie
        working_directory: /home/circleci/test
        steps:
            - run:
                  name: Install awscli
                  command: sudo pip install awscli
            - restore_cache:
                  key: dependency-test-{{ .Environment.CIRCLE_SHA1 }}
            - run: aws s3 sync /home/circleci/duo-contract-wrapper/coverage/lcov-report s3://duo-contract-wrapper
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - deploy:
                requires:
                    - build
    schedule_deploy:
        triggers:
            - schedule:
                  cron: '0 4 * * *'
                  filters:
                      branches:
                          only: master
        jobs:
            - build
            - deploy:
                requires:
                    - build